---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ykw.
--- DateTime: 2025-12-18 4:56 p.m.
---
if (redis.call('get', KEYS[1])  == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0